baseURL = '{{BASE_URL}}'
locale = 'ko-kr'
title = '{{SITE_TITLE}}'
theme = 'PaperMod'
paginate = 10

[params]
  env = 'production'
  title = '{{SITE_TITLE}}'
  description = '{{SITE_DESCRIPTION}}'
  author = '{{GITHUB_USER}}'
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = '{{HOME_TITLE}}'
    Content = '{{HOME_DESCRIPTION}}'

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/{{GITHUB_USER}}/{{REPO_NAME}}'

[menu]
  [[menu.main]]
    identifier = 'input'
    name = '{{INPUT_BUTTON_LABEL}}'
    url = 'https://github.com/{{GITHUB_USER}}/{{REPO_NAME}}/edit/main/input/sentence.md'
    weight = 5
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 20
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/'
    weight = 30

[outputs]
  home = ['HTML', 'RSS', 'JSON']
